# Generated by Django 4.2.3 on 2024-10-15 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('faces_detected', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
